version: '3.9'

services:
  spanglish-api:
    container_name: Spanglish-API
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run python manage.py runserver 0.0.0.0:8000