# Generated by Django 5.2.5 on 2025-08-11 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('verb', 'Verb'), ('noun', 'Noun'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('pron', 'Pronoun')], max_length=10)),
                ('categories', models.ManyToManyField(blank=True, related_name='words', to='dictionary.category')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verb_info', to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('related_words', models.ManyToManyField(blank=True, related_name='sentences', to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='VerbConjugation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(choices=[('present', 'Present'), ('past', 'Past'), ('future', 'Future'), ('preterite', 'Preterite'), ('imperfect', 'Imperfect'), ('conditional', 'Conditional'), ('subjunctive', 'Subjunctive')], max_length=20)),
                ('person', models.CharField(choices=[('1s', 'First Person Singular (yo)'), ('2s', 'Second Person Singular (tú)'), ('3s', 'Third Person Singular (él/ella/usted)'), ('1p', 'First Person Plural (nosotros)'), ('2p', 'Second Person Plural (vosotros)'), ('3p', 'Third Person Plural (ellos/ellas/ustedes)')], max_length=2)),
                ('conjugated_form', models.CharField(max_length=100)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjugations', to='dictionary.verb')),
            ],
            options={
                'unique_together': {('verb', 'tense', 'person')},
            },
        ),
    ]
